/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerificationEmailRouteImport } from './routes/verification-email'
import { Route as AuthedCompteRouteImport } from './routes/_authed/compte'
import { Route as AuthedDeposerRouteImport } from './routes/_authed/deposer'
import { Route as AuthedMesAnnoncesRouteImport } from './routes/_authed/mes-annonces'
import { Route as AuthedModerationRouteImport } from './routes/_authed/moderation'
import { Route as AnnoncesListingIdRouteImport } from './routes/annonces/$listingId'
import { Route as AuthedAnnoncesListingIdModifierRouteImport } from './routes/_authed/annonces/$listingId/modifier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationEmailRoute = VerificationEmailRouteImport.update({
  id: '/verification-email',
  path: '/verification-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCompteRoute = AuthedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeposerRoute = AuthedDeposerRouteImport.update({
  id: '/deposer',
  path: '/deposer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMesAnnoncesRoute = AuthedMesAnnoncesRouteImport.update({
  id: '/mes-annonces',
  path: '/mes-annonces',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedModerationRoute = AuthedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthedRoute,
} as any)
const AnnoncesListingIdRoute = AnnoncesListingIdRouteImport.update({
  id: '/annonces/$listingId',
  path: '/annonces/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAnnoncesListingIdModifierRoute =
  AuthedAnnoncesListingIdModifierRouteImport.update({
    id: '/annonces/$listingId/modifier',
    path: '/annonces/$listingId/modifier',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/cookies': typeof CookiesRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/recherche': typeof RechercheRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification-email': typeof VerificationEmailRoute
  '/compte': typeof AuthedCompteRoute
  '/deposer': typeof AuthedDeposerRoute
  '/mes-annonces': typeof AuthedMesAnnoncesRoute
  '/moderation': typeof AuthedModerationRoute
  '/annonces/$listingId': typeof AnnoncesListingIdRoute
  '/annonces/$listingId/modifier': typeof AuthedAnnoncesListingIdModifierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/cookies': typeof CookiesRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/recherche': typeof RechercheRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification-email': typeof VerificationEmailRoute
  '/compte': typeof AuthedCompteRoute
  '/deposer': typeof AuthedDeposerRoute
  '/mes-annonces': typeof AuthedMesAnnoncesRoute
  '/moderation': typeof AuthedModerationRoute
  '/annonces/$listingId': typeof AnnoncesListingIdRoute
  '/annonces/$listingId/modifier': typeof AuthedAnnoncesListingIdModifierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/cookies': typeof CookiesRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/recherche': typeof RechercheRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification-email': typeof VerificationEmailRoute
  '/_authed/compte': typeof AuthedCompteRoute
  '/_authed/deposer': typeof AuthedDeposerRoute
  '/_authed/mes-annonces': typeof AuthedMesAnnoncesRoute
  '/_authed/moderation': typeof AuthedModerationRoute
  '/annonces/$listingId': typeof AnnoncesListingIdRoute
  '/_authed/annonces/$listingId/modifier': typeof AuthedAnnoncesListingIdModifierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/connexion'
    | '/cookies'
    | '/inscription'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/recherche'
    | '/reinitialiser-mot-de-passe'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verification-email'
    | '/compte'
    | '/deposer'
    | '/mes-annonces'
    | '/moderation'
    | '/annonces/$listingId'
    | '/annonces/$listingId/modifier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/confidentialite'
    | '/connexion'
    | '/cookies'
    | '/inscription'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/recherche'
    | '/reinitialiser-mot-de-passe'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verification-email'
    | '/compte'
    | '/deposer'
    | '/mes-annonces'
    | '/moderation'
    | '/annonces/$listingId'
    | '/annonces/$listingId/modifier'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/cgu'
    | '/confidentialite'
    | '/connexion'
    | '/cookies'
    | '/inscription'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/recherche'
    | '/reinitialiser-mot-de-passe'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verification-email'
    | '/_authed/compte'
    | '/_authed/deposer'
    | '/_authed/mes-annonces'
    | '/_authed/moderation'
    | '/annonces/$listingId'
    | '/_authed/annonces/$listingId/modifier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  CookiesRoute: typeof CookiesRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  RechercheRoute: typeof RechercheRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerificationEmailRoute: typeof VerificationEmailRoute
  AnnoncesListingIdRoute: typeof AnnoncesListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-email': {
      id: '/verification-email'
      path: '/verification-email'
      fullPath: '/verification-email'
      preLoaderRoute: typeof VerificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/compte': {
      id: '/_authed/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthedCompteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deposer': {
      id: '/_authed/deposer'
      path: '/deposer'
      fullPath: '/deposer'
      preLoaderRoute: typeof AuthedDeposerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/mes-annonces': {
      id: '/_authed/mes-annonces'
      path: '/mes-annonces'
      fullPath: '/mes-annonces'
      preLoaderRoute: typeof AuthedMesAnnoncesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/moderation': {
      id: '/_authed/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthedModerationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/annonces/$listingId': {
      id: '/annonces/$listingId'
      path: '/annonces/$listingId'
      fullPath: '/annonces/$listingId'
      preLoaderRoute: typeof AnnoncesListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/annonces/$listingId/modifier': {
      id: '/_authed/annonces/$listingId/modifier'
      path: '/annonces/$listingId/modifier'
      fullPath: '/annonces/$listingId/modifier'
      preLoaderRoute: typeof AuthedAnnoncesListingIdModifierRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCompteRoute: typeof AuthedCompteRoute
  AuthedDeposerRoute: typeof AuthedDeposerRoute
  AuthedMesAnnoncesRoute: typeof AuthedMesAnnoncesRoute
  AuthedModerationRoute: typeof AuthedModerationRoute
  AuthedAnnoncesListingIdModifierRoute: typeof AuthedAnnoncesListingIdModifierRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCompteRoute: AuthedCompteRoute,
  AuthedDeposerRoute: AuthedDeposerRoute,
  AuthedMesAnnoncesRoute: AuthedMesAnnoncesRoute,
  AuthedModerationRoute: AuthedModerationRoute,
  AuthedAnnoncesListingIdModifierRoute: AuthedAnnoncesListingIdModifierRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  CookiesRoute: CookiesRoute,
  InscriptionRoute: InscriptionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  RechercheRoute: RechercheRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerificationEmailRoute: VerificationEmailRoute,
  AnnoncesListingIdRoute: AnnoncesListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
